<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Launching browser]]>
    </line>
    <line>
      <![CDATA[Browser launching success]]>
    </line>
    <line>
      <![CDATA[launching succesfully]]>
    </line>
    <line>
      <![CDATA[login succefully]]>
    </line>
    <line>
      <![CDATA[test start]]>
    </line>
    <line>
      <![CDATA[test failed]]>
    </line>
    <line>
      <![CDATA[Browser closed success]]>
    </line>
  </reporter-output>
  <suite started-at="2022-04-02T12:39:47 IST" name="Default suite" finished-at="2022-04-02T12:39:58 IST" duration-ms="10946">
    <groups>
    </groups>
    <test started-at="2022-04-02T12:39:47 IST" name="Default test" finished-at="2022-04-02T12:39:58 IST" duration-ms="10946">
      <class name="test_classes.Test3">
        <test-method is-config="true" signature="launchingbrowser()[pri:0, instance:test_classes.Test3@f09733f]" started-at="2022-04-02T12:39:48 IST" name="launchingbrowser" finished-at="2022-04-02T12:39:54 IST" duration-ms="6185" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Launching browser]]>
            </line>
            <line>
              <![CDATA[Browser launching success]]>
            </line>
            <line>
              <![CDATA[launching succesfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- launchingbrowser -->
        <test-method is-config="true" signature="loginkite()[pri:0, instance:test_classes.Test3@f09733f]" started-at="2022-04-02T12:39:54 IST" name="loginkite" finished-at="2022-04-02T12:39:55 IST" duration-ms="904" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[login succefully]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginkite -->
        <test-method signature="Validateusername()[pri:0, instance:test_classes.Test3@f09733f]" started-at="2022-04-02T12:39:55 IST" name="Validateusername" finished-at="2022-04-02T12:39:57 IST" duration-ms="1945" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[username not matching  expected [421113] but found [GPQ493]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: username not matching  expected [421113] but found [GPQ493]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at test_classes.Test3.Validateusername(Test3.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[test start]]>
            </line>
            <line>
              <![CDATA[test failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- Validateusername -->
        <test-method is-config="true" signature="logout()[pri:0, instance:test_classes.Test3@f09733f]" started-at="2022-04-02T12:39:57 IST" name="logout" finished-at="2022-04-02T12:39:58 IST" duration-ms="1722" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="close()[pri:0, instance:test_classes.Test3@f09733f]" started-at="2022-04-02T12:39:58 IST" name="close" finished-at="2022-04-02T12:39:58 IST" duration-ms="105" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Browser closed success]]>
            </line>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- test_classes.Test3 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
